---
- name: High CPU Load Test
  hosts: your_target_server  # Replace with the hostname or IP address of your target server
  gather_facts: no
  tasks:
    - name: Run High CPU Load
      shell: |
        while true; do
          openssl speed rsa2048;
        done
      async: 3600  # Run for an hour (adjust as needed)
      poll: 0
