---
- name: CPU Intensive Load Test
  hosts: all  # Replace with the hosts or inventory group you want to target
  gather_facts: no  # Skip gathering facts to speed up execution

  tasks:
    - name: Generate CPU Load
      shell: "openssl speed rsa4096"
