---
- name: Install Apache HTTP Server
  hosts: webservers # Replace with the hostname or IP address of your target server
  gather_facts: no
  become: yes  # Enable privilege escalation (sudo)

  tasks:

    - name: Set environment variable for a task
      command: echo "This is a task with a custom environment variable"
      environment:
        MY_ENV_VARIABLE: "true"    

    - name: Debug environment variable
      debug:
        var: MY_ENV_VARIABLE

    - name: Update package cache
      apt:
        update_cache: yes  # For Debian/Ubuntu-based systems
      environment:
        webservers: "true"

    - name: Install Apache
      apt:
        name: apache2  # Package name for Apache
        state: present  # Ensure Apache is installed
      when: webservers == 'true'

    - name: Start Apache and enable on boot
      systemd:
        name: apache2
        enabled: yes
        state: started
      when: webservers == 'true'

    - name: Ensure Apache service is running
      systemd:
        name: apache2
        state: started
      when: webservers == 'true'
