---
- name: Install Apache HTTP Server
  hosts: webservers # Replace with the hostname or IP address of your target server
  gather_facts: no
  become: yes  # Enable privilege escalation (sudo)

  tasks:

    - name: Run a Command to Check Environment Variable
      command: echo $webservers  # Replace with the variable name you want to check
      register: env_variable_output

    - name: Print Environment Variable Value
      debug:
        var: env_variable_output.stdout


    - name: Update package cache
      apt:
        update_cache: yes  # For Debian/Ubuntu-based systems
      when: lookup('env', 'webservers') == '*'

    - name: Install Apache
      apt:
        name: apache2  # Package name for Apache
        state: present  # Ensure Apache is installed
      when: webservers == 'true'

    - name: Start Apache and enable on boot
      systemd:
        name: apache2
        enabled: yes
        state: started
      when: webservers == 'true'

    - name: Ensure Apache service is running
      systemd:
        name: apache2
        state: started
      when: webservers == 'true'
