---
- name: Install Apache HTTP Server
  hosts: all # Replace with the hostname or IP address of your target server
  gather_facts: no
  become: yes  # Enable privilege escalation (sudo)

  tasks:

    - name: Install Apache
      apt:
        name: apache2  # Package name for Apache
        state: present  # Ensure Apache is installed

    - name: Start Apache and enable on boot
      systemd:
        name: apache2
        enabled: yes
        state: started

    - name: Ensure Apache service is running
      systemd:
        name: apache2
        state: started
