---

- name: Sudo access  
  hosts: "{{ ansible_limit | default('localhost') }}"
  vars:
     filepath: /etc/sudoers.d/sudo-access     
  gather_facts: no
  tasks:    

     # - name: assert limit
     #   run_once: yes
     #   assert:
     #    that:
     #    - 'ansible_limit is defined'
     #    fail_msg: Playbook must be run with a limit (normally staging or production)
     #    quiet: yes
       
     - name: create sudo file if the file does not exist
       file:
          path: "{{ filepath }}"
          owner: root
          group: root
          mode: '0644'
          state: touch
       become: yes
       register: filestat
       ignore_unreachable: True
       ignore_errors: True

     - name:  Add sudo access to the file
       lineinfile:
          path: "{{ filepath }}"
          line: "testuser ALL=(ALL) NOPASSWD:ALL"
          validate: /usr/sbin/visudo -cf %s
       become: yes
       register: appendstat
       ignore_unreachable: True
       ignore_errors: True
       when: filestat is not unreachable and filestat.failed == false
