apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
  namespace: docker-registry
spec:
  type: LoadBalancer
  selector:    
     run: registry
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 5000