apiVersion: v1
kind: Pod
metadata:
  name: mywebapp1
  labels:
    demo: kubelabs
spec:
  serviceAccountName: sshprivatekey
  automountServiceAccountToken: true
  containers:
  - name: mycontainer
    image: docker.io/httpd
    ports:
    - containerPort: 80
