name: Ansible Playbook Validation

on:
  # Triggers for the workflow
  push:
    branches: [ "main" ]  # Modify as needed
  pull_request:
    branches: [ "main" ]  # Modify as needed

jobs:
  check_ansible_playbooks:
    # Define the environment for the job
    runs-on: ansible-awx  # Use the latest Ubuntu runner for CI

    steps:
      # Step to check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step to install Ansible
      - name: Install Ansible
        run: |           
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update
          sudo apt-get install -y ansible

      # Step to check for prohibited host pattern in playbooks
      - name: Check for host all is set
        run: |
          # Check all YAML files for host for all
          for file in $(find . -name '*.ymll'); do
            if [[ "$file" == "./.github/workflows/main.yml" ]]; then
              # Skip the specific file
              continue
            fi
          
            if grep -q "hosts: all" "$file"; then
              echo "Error: Playbook $file contains invalid host pattern."
              exit 1  # Exit with error if found
            fi
          done

