name: Ansible Playbook Validation

on:
  # Triggers for the workflow
  push:
    branches: [ "main" ]  # Modify as needed
  pull_request:
    branches: [ "main" ]  # Modify as needed

jobs:
  check_ansible_playbooks:
    # Define the environment for the job
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for CI

    steps:
      # Step to check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step to install Ansible
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      # Step to check for prohibited 'hosts: all' pattern in playbooks
      - name: Check for 'hosts: all'
        run: |
          # Check all YAML files for 'hosts: all'
          for file in $(find . -name '*.yml'); do
            if grep -q "hosts: all" "$file"; then
              echo "Error: Playbook $file contains 'hosts: all'."
              exit 1  # Exit with error if found
            fi
          done

      # Step to run Ansible syntax checks on all playbooks in the repo
      - name: Run Ansible Syntax Check
        run: |
          for file in $(find . -name '*.yml'); do
            ansible-playbook --syntax-check "$file"
          done
